export const adminMenu = [
  {
    slug: "conta-recebimento",
    title: "Conta para receber pagamentos",
    category: "Pagamentos",
    href: "/menu/conta-recebimento",
  },
  {
    slug: "homologacao-pagbank",
    title: "Homologação PagBank",
    category: "Pagamentos",
    href: "/menu/homologacao-pagbank",
  },
  {
    slug: "pesquisar-participantes",
    title: "Pesquisar participantes",
    category: "Participantes",
    href: "/menu/pesquisar-participantes",
  },
  {
    slug: "filtrar-participantes",
    title: "Filtrar participantes",
    category: "Participantes",
    href: "/menu/filtrar-participantes",
  },
  {
    slug: "editar-participante",
    title: "Editar participante",
    category: "Participantes",
    href: "/menu/editar-participante",
  },
  {
    slug: "corrigir-parcela",
    title: "Corrigir parcelas",
    category: "Financeiro",
    href: "/menu/corrigir-parcela",
  },
  {
    slug: "estornar-pagamento",
    title: "Estornar pagamento",
    category: "Financeiro",
    href: "/menu/estornar-pagamento",
  },
  {
    slug: "historico-parcelas",
    title: "Histórico de parcelas",
    category: "Financeiro",
    href: "/menu/historico-parcelas",
  },
  {
    slug: "relatorio-inadimplentes",
    title: "Relatório de pendentes",
    category: "Relatórios",
    href: "/menu/relatorio-inadimplentes",
  },
  {
    slug: "distribuir-premios",
    title: "Distribuir prêmios",
    category: "Prêmios",
    href: "/menu/distribuir-premios",
  },
  {
    slug: "creditar-premio",
    title: "Converter prêmio em crédito",
    category: "Prêmios",
    href: "/menu/creditar-premio",
  },
  {
    slug: "mensagens-cobranca",
    title: "Mensagens de cobrança",
    category: "Comunicação",
    href: "/menu/mensagens-cobranca",
  },
  {
    slug: "avisos-parciais",
    title: "Avisos de pagamento parcial",
    category: "Comunicação",
    href: "/menu/avisos-parciais",
  },
  {
    slug: "painel-erros",
    title: "Painel de erros",
    category: "Sistema",
    href: "/menu/painel-erros",
  },
  {
    slug: "backup",
    title: "Backup e restauração",
    category: "Sistema",
    href: "/menu/backup",
  },
  {
    slug: "documentos-legais",
    title: "Privacidade, Termos e LGPD",
    category: "Sistema",
    href: "/menu/documentos-legais",
  },
] as const;
