import Link from "next/link";
import {AppNav} from "@/components/app-nav";
import {OrganizerCta} from "@/components/organizer-cta";
import {DashboardIcon} from "@/components/dashboard-icon";
import {Greeting} from "@/components/greeting";
import {OrganizerActivityToasts} from "@/components/organizer-activity-toasts";
import {OrganizerNotificationOptIn} from "@/components/organizer-notification-opt-in";
import {MegaAnimatedCover} from "@/components/mega-animated-cover";
import {createClient} from "@/lib/supabase/server";
import {DEFAULT_APP_BRAND,getOrganizerBrand} from "@/lib/organizer-brand";

export const dynamic="force-dynamic";
const money=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
type Pool={id:string;title:string;lottery:string;total_shares:number;share_price_cents:number;public_slug:string|null;status:string;cover_image_url:string|null};
const statusLabel=(s:string)=>({open:"Aberto",closed:"Encerrado",draft:"Rascunho"}[s]??s);
const lotteryImage=(s:string)=>s.toLowerCase().includes("mega")?"/lottery-mega.svg":"/icon.svg";
const isMegaDaVirada=(p:Pool)=>p.title.toLowerCase().includes("mega da virada");
const Brand=({label,name=DEFAULT_APP_BRAND,logoUrl}:{label:string;name?:string;logoUrl?:string})=><div className="brand"><strong style={{display:"inline-flex",alignItems:"center",gap:10}}><img src={logoUrl||"/icon.svg"} alt={name} width="48" height="48" style={{borderRadius:12,objectFit:"cover"}}/><span>{name}</span></strong><span className="badge">{label}</span></div>;
const menu=[
 ["identity","Minha identidade","Nome da marca e domínio futuro","/organizador/perfil"],
 ["wallet","Carteira","Arrecadação transparente","/carteira"],
 ["ticket","Jogos","Apostas e comprovantes","/jogos"],
 ["check","Conferência","Resultados e acertos","/conferencia"],
 ["users","Participantes","Gerencie participantes","/participantes"],
 ["generator","Gerar Jogos","Crie combinações","/meu-jogo"],
 ["archive","Jogos Salvos","Consulte e confira resultados","/jogos-salvos"],
 ["message","Mensagens","Bugs, sugestões e ajuda","/mensagens"]
] as const;

export default async function Home({searchParams}:{searchParams:Promise<{pool?:string}>}){
 const {pool:requested}=await searchParams;const s=await createClient();const {data:auth}=await s.auth.getUser();
 if(!auth.user)return <main className="shell"><Brand label="Online"/><section className="hero"><h1>Acompanhe o próximo bolão.</h1><p className="muted">Mesmo antes de o organizador publicar o bolão, você pode acompanhar o temporizador e ativar os lembretes neste celular.</p><Link className="button primary" href="/temporizador">VER TEMPORIZADOR</Link></section><OrganizerCta/><section className="section"><h2>Já é organizador?</h2><Link className="button secondary" href="/login">Entrar como organizador</Link></section></main>;
 const organizerBrand=await getOrganizerBrand(s,auth.user.id);let pools:Pool[]=[];let paid=0,pending=0,collected=0,unreadMessages=0;
 const {data}=await s.from("pools").select("id,title,lottery,total_shares,share_price_cents,public_slug,status,cover_image_url").eq("owner_id",auth.user.id).order("created_at",{ascending:false});pools=(data??[]) as Pool[];const activePools=[...pools.filter(p=>p.status==="open"),...pools.filter(p=>p.status!=="open"&&p.status!=="closed")];const closedPools=pools.filter(p=>p.status==="closed");const pool=activePools.find(p=>p.id===requested)??activePools[0]??null;
 if(pools.length){const{count}=await s.from("participant_support_messages").select("id",{count:"exact",head:true}).in("pool_id",pools.map(p=>p.id)).eq("status","unread");unreadMessages=count??0;}
 if(pool){const [{data:parts},{data:wallet}]=await Promise.all([s.from("participants").select("shares,payment_status,status").eq("pool_id",pool.id),s.from("wallet_transactions").select("amount_cents").eq("pool_id",pool.id)]);for(const p of parts??[]){if(p.status==="cancelled")continue;const n=Number(p.shares)||0;p.payment_status==="confirmed"?paid+=n:pending+=n;}collected=(wallet??[]).reduce((a,x)=>a+Number(x.amount_cents||0),0);}
 const total=pool?pool.total_shares*pool.share_price_cents:0,progress=total?Math.min(100,Math.round(collected/total*100)):0,q=pool?`?pool=${encodeURIComponent(pool.id)}`:"",timerHref=pool?.public_slug?`/temporizador/${pool.public_slug}`:"/temporizador";
 const organizerName=String(auth.user.user_metadata?.full_name??auth.user.user_metadata?.name??auth.user.email?.split("@")[0]??organizerBrand.name);
 return <main className="shell"><Brand label="Organizador" name={organizerBrand.name} logoUrl={organizerBrand.logoUrl}/><Greeting name={organizerName}/><section className="hero"><h1>Painel do organizador</h1><p className="muted">Crie o bolão, compartilhe o link e acompanhe automaticamente participantes, pagamentos, carteira e jogos. Seus dados ficam separados dos demais organizadores.</p><div className="actions"><Link className="button primary" style={{fontSize:20}} href="/criar-bolao">+ Criar bolão</Link></div></section><OrganizerNotificationOptIn/>
 {activePools.length>0&&<section className="section"><h2>Meus bolões</h2><div className="pool-carousel" role="region" aria-label="Meus bolões — deslize para ver os demais">{activePools.map(p=>{const active=p.id===pool?.id;const cover=p.cover_image_url||(isMegaDaVirada(p)?"/mega-da-virada-2026.webp":null);if(cover)return <Link key={p.id} className="pool-carousel-card" href={`/?pool=${p.id}`} aria-label={`${p.title} — ${statusLabel(p.status)}`} style={{overflow:"hidden",display:"block",textDecoration:"none",border:`${active?2:1}px solid ${active?"#f7c948":"rgba(247,201,72,.6)"}`,borderRadius:20,background:"#061009",boxShadow:"inset 0 1px 0 rgba(255,236,159,.12),0 8px 20px rgba(0,0,0,.28)"}}>{isMegaDaVirada(p)&&!p.cover_image_url?<MegaAnimatedCover src={cover} alt={`${p.title} — ${statusLabel(p.status)}`} animate={p.status==="open"}/>:<img src={cover} alt={`${p.title} — ${statusLabel(p.status)}`} style={{width:"100%",height:"auto",aspectRatio:"3 / 1",display:"block",objectFit:"cover"}}/>}</Link>;return <Link key={p.id} className="pool-carousel-card" href={`/?pool=${p.id}`} style={{height:116,position:"relative",overflow:"hidden",display:"grid",gridTemplateColumns:"42% 1fr auto auto",alignItems:"center",gap:8,textDecoration:"none",color:"#fff",border:`${active?2:1}px solid ${active?"#f7c948":"rgba(247,201,72,.6)"}`,borderRadius:20,background:"radial-gradient(circle at 18% 50%,#193d24 0,#0a1c10 42%,#061009 100%)",boxShadow:"inset 0 1px 0 rgba(255,236,159,.12),0 8px 20px rgba(0,0,0,.28)"}}><span style={{alignSelf:"stretch",overflow:"hidden",display:"block"}}><img src={lotteryImage(p.lottery)} alt="" style={{width:"100%",height:"100%",display:"block",objectFit:"cover"}}/></span><strong style={{fontSize:22,lineHeight:1.02,textTransform:"uppercase",fontWeight:900,textShadow:"0 2px 2px #000",background:"linear-gradient(180deg,#fff7d0 0%,#ffd84d 45%,#d89a00 100%)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>{p.title}</strong><span style={{border:"1px solid rgba(247,201,72,.65)",borderRadius:999,padding:"7px 12px",color:"#f7c948",fontSize:13,fontWeight:800,whiteSpace:"nowrap"}}>{statusLabel(p.status)}</span><span style={{color:"#f7c948",fontSize:32,fontWeight:300,paddingRight:10}}>›</span></Link>})}</div></section>}
 {closedPools.length>0&&<section className="section closed-pools-notice"><Link className="card pool-history-link" href="/historico-bolao"><span><strong>Histórico de bolões</strong><span>{closedPools.length} {closedPools.length===1?"bolão encerrado":"bolões encerrados"} guardado(s)</span></span><span className="card-chevron">›</span></Link></section>}
 <section className="section"><h2>Gerenciar {pool?pool.title:"bolão"}</h2><div className="grid dashboard-grid">{menu.map(([icon,title,sub,href])=>{const withPool=["/carteira","/jogos","/conferencia","/participantes"].includes(href);return <Link key={title} className="card dashboard-card" href={withPool?`${href}${q}`:href}><DashboardIcon name={icon}/><span className="card-copy"><strong>{title}{href==="/mensagens"&&unreadMessages>0?<b className="message-unread-badge">{unreadMessages>99?"99+":unreadMessages}</b>:null}</strong><span>{sub}</span></span><span className="card-chevron">›</span></Link>})}{pool&&<Link className="card dashboard-card" href={`/organizador/bolao/${pool.id}/imagem`}><DashboardIcon name="image"/><span className="card-copy"><strong>Imagem do bolão</strong><span>Trocar ou remover a capa</span></span><span className="card-chevron">›</span></Link>}<Link className="card dashboard-card" href={timerHref}><DashboardIcon name="timer"/><span className="card-copy"><strong>Temporizador</strong><span>{pool?.public_slug?"Compartilhe o prazo":"Acompanhe o prazo"}</span></span><span className="card-chevron">›</span></Link></div></section>
 <section className="section summary-section">{pool?<div className="wallet summary-card"><span className="summary-clover" aria-hidden="true">🍀</span><div className="summary-content"><h2>{pool.title}</h2><div className="summary-value"><strong>{money(collected)}</strong><span>arrecadados</span></div><div className="summary-stats"><div><strong>{paid}</strong><span>{paid===1?"cota paga":"cotas pagas"}</span></div><div><strong>{pending}</strong><span>pendentes</span></div></div><div className="summary-progress-head"><strong>{progress}%</strong><span>Meta: {money(total)}</span></div><div className="progress" aria-label={`${progress}% da meta arrecadada`}><div style={{width:`${progress}%`}}/></div></div></div>:<p className="muted">Você ainda não criou um bolão. O temporizador de pré-abertura continua disponível para os participantes.</p>}</section><OrganizerActivityToasts startedAt={new Date(Date.now()-5000).toISOString()}/><AppNav/></main>;
}
