import Link from "next/link";
import {createAdminClient} from "@/lib/supabase/admin";
import {PoolCountdown} from "@/components/pool-countdown";
import {TimerReminderOptIn} from "@/components/timer-reminder-opt-in";
import {OrganizerCta} from "@/components/organizer-cta";
import {ScrollPageTop} from "@/components/scroll-page-top";
import {getOrganizerBrand} from "@/lib/organizer-brand";
export const dynamic="force-dynamic";
const money=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
export default async function TimerPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;try{const s=createAdminClient();const{data:pool,error}=await s.from("pools").select("id,owner_id,title,lottery,contest_number,estimated_prize_cents,share_price_cents,total_shares,payment_opens_at,payment_deadline,draw_at,status,public_slug,planned_games,numbers_per_game").eq("public_slug",slug).maybeSingle();if(error)throw error;if(!pool)return <main className="shell"><section className="section"><h1>Bolão não encontrado</h1></section></main>;
const brand=await getOrganizerBrand(s,pool.owner_id);const[{data:participants},{data:games}]=await Promise.all([s.from("participants").select("shares,status").eq("pool_id",pool.id),s.from("games").select("id,numbers").eq("pool_id",pool.id)]);const confirmed=(participants??[]).filter(p=>p.status==="confirmed"),used=confirmed.reduce((a,p)=>a+(Number(p.shares)||0),0),available=Math.max(0,Number(pool.total_shares)-used);const now=Date.now(),opens=pool.payment_opens_at?new Date(pool.payment_opens_at).getTime():0,closes=new Date(pool.payment_deadline).getTime(),draw=pool.draw_at?new Date(pool.draw_at).getTime():0;const beforeOpen=opens>now,windowOpen=!beforeOpen&&now<closes,afterClose=now>=closes;const planned=Number(pool.planned_games)||(games?.length??0),numbers=Number(pool.numbers_per_game)||(Array.isArray(games?.[0]?.numbers)?games![0].numbers.length:0);const canJoin=pool.status==="open"&&!afterClose;
return <main className="shell"><ScrollPageTop/><section className="section" style={{textAlign:"center"}}><p className="eyebrow">{brand.name.toUpperCase()}</p><h1>🍀 {pool.title}</h1><p className="muted">{pool.lottery}{pool.contest_number?` · Concurso ${pool.contest_number}`:""}</p></section>
<section className="section">{beforeOpen?<><p className="eyebrow" style={{textAlign:"center"}}>FALTAM PARA ABRIR OS PAGAMENTOS</p><PoolCountdown target={pool.payment_opens_at}/><p className="muted" style={{textAlign:"center"}}>🔒 Pix e comprovante ficam fechados até {new Date(pool.payment_opens_at).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}.</p></>:windowOpen?<><p className="eyebrow" style={{textAlign:"center"}}>🟢 PAGAMENTOS ABERTOS</p><h2 style={{textAlign:"center"}}>Falta para o encerramento</h2><PoolCountdown target={pool.payment_deadline}/></>:<><p className="eyebrow" style={{textAlign:"center"}}>🔴 PAGAMENTOS ENCERRADOS</p>{draw>now?<><h2 style={{textAlign:"center"}}>Falta para o sorteio</h2><PoolCountdown target={pool.draw_at}/></>:<p className="muted" style={{textAlign:"center"}}>O prazo de pagamento deste bolão terminou.</p>}</>}</section>
{beforeOpen&&<TimerReminderOptIn slug={slug}/>}<section className="section"><div className="wallet">{pool.estimated_prize_cents?<div className="wallet-row"><span>🏆 Prêmio estimado</span><strong>{money(Number(pool.estimated_prize_cents))}</strong></div>:null}<div className="wallet-row"><span>👥 Participantes</span><strong>{confirmed.length} / {pool.total_shares}</strong></div><div className="wallet-row"><span>🎟️ Vagas disponíveis</span><strong>{available}</strong></div><div className="wallet-row"><span>🎯 Jogos planejados</span><strong>{planned}</strong></div><div className="wallet-row"><span>🧾 Jogos cadastrados</span><strong>{games?.length??0} / {planned}</strong></div>{numbers?<div className="wallet-row"><span>🔢 Dezenas por jogo</span><strong>{numbers}</strong></div>:null}<div className="wallet-row"><span>💵 Valor da participação</span><strong>{money(Number(pool.share_price_cents))}</strong></div><div className="wallet-row"><span>💳 Pagamento</span><strong>{beforeOpen?"🔒 Fechado":windowOpen?"🟢 Liberado":"🔴 Encerrado"}</strong></div>{pool.draw_at?<div className="wallet-row"><span>📅 Sorteio</span><strong>{new Date(pool.draw_at).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</strong></div>:null}</div></section>
<section className="section" style={{textAlign:"center"}}>{canJoin?<><h2>{available>0?"Quer participar?":"⏳ Lista de espera aberta"}</h2><p className="muted">{available>0?`Reserve sua participação agora. ${beforeOpen?"O pagamento será liberado automaticamente na data indicada.":"Os pagamentos já estão abertos."}`:"As vagas principais foram preenchidas. Novos participantes podem entrar na lista de espera e só pagam se uma vaga for liberada."}</p><Link className="button primary" href={`/bolao/${slug}`}>{available>0?"🍀 PARTICIPAR DO BOLÃO":"⏳ ENTRAR NA LISTA DE ESPERA"}</Link></>:<><h2>Participação indisponível</h2><p className="muted">{afterClose?"O prazo de pagamento terminou.":"Este bolão não está aberto."}</p></>}</section><OrganizerCta/></main>}catch{return <main className="shell"><section className="section"><h1>Temporizador indisponível</h1><p className="muted">Não foi possível carregar este bolão.</p></section></main>}}
