"use client";
import {useEffect,useState} from "react";
import {ensureCurrentPushSubscription} from "@/lib/push/browser-subscription";

type Props={slug?:string;campaignKey?:string};
function withTimeout<T>(promise:Promise<T>,ms=12000):Promise<T>{
 return Promise.race([promise,new Promise<T>((_,reject)=>window.setTimeout(()=>reject(new Error("timeout")),ms))]);
}
export function TimerReminderOptIn({slug,campaignKey}:Props){
 const[visible,setVisible]=useState(false);const[state,setState]=useState<"checking"|"idle"|"busy"|"error">("checking");const identity=slug||campaignKey||"";const reminderText=campaignKey?"a abertura do próximo bolão":"a abertura dos pagamentos";const choiceKey=`bolao-amigos-btp:reminder-choice:${identity||"geral"}`;
 useEffect(()=>{let cancelled=false;let timer:number|undefined;const prepare=async()=>{try{const choice=window.localStorage.getItem(choiceKey);if(choice==="declined"){if(!cancelled){setState("idle");setVisible(false)}return}if(choice==="accepted"){if(!identity||!("serviceWorker" in navigator)||!("PushManager" in window)){if(!cancelled){setState("idle");setVisible(false)}return}const reg=await navigator.serviceWorker.ready;const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(publicKey&&Notification.permission==="granted"){const sub=await ensureCurrentPushSubscription(reg,publicKey);await fetch("/api/push/timer-subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,campaignKey,subscription:sub.toJSON()})})}if(!cancelled){setState("idle");setVisible(false)}return}if(!cancelled){setState("idle");timer=window.setTimeout(()=>setVisible(true),8000)}}catch{if(!cancelled){setState("idle");timer=window.setTimeout(()=>setVisible(true),8000)}}};prepare();return()=>{cancelled=true;if(timer)window.clearTimeout(timer)}},[identity,slug,campaignKey,choiceKey]);
 const decline=()=>{try{window.localStorage.setItem(choiceKey,"declined")}catch{}setVisible(false);setState("idle")};
 const enable=async()=>{if(state==="busy")return;try{setState("busy");if(!identity||!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw new Error("unsupported");const permission=Notification.permission==="granted"?"granted":await withTimeout(Notification.requestPermission());if(permission!=="granted")throw new Error("permission");const reg=await withTimeout(navigator.serviceWorker.ready,10000);const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error("key");const sub=await withTimeout(ensureCurrentPushSubscription(reg,publicKey));const res=await withTimeout(fetch("/api/push/timer-subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,campaignKey,subscription:sub.toJSON()})}),10000);if(!res.ok)throw new Error("server");try{window.localStorage.setItem(choiceKey,"accepted")}catch{}setVisible(false);setState("idle")}catch{setState("error")}};
 if(!visible||state==="checking")return null;
 return <div className="reminder-fixed-overlay" role="dialog" aria-modal="true" aria-label="Ativar lembretes"><div className="reminder-fixed-card"><h2>🔔 Quer receber lembretes deste bolão?</h2><p className="muted">Ative neste celular para receber um lembrete a cada 10 dias até {reminderText}.</p><button className="button reminder-3d" type="button" disabled={state==="busy"} onClick={enable}>{state==="busy"?"Ativando...":"🔔 ATIVAR LEMBRETES"}</button><button className="reminder-decline" type="button" onClick={decline}>{state==="error"?"FECHAR":"Agora não"}</button>{state==="error"&&<p className="muted">Não foi possível ativar. Abra este link no Google Chrome e permita as notificações nas configurações do site.</p>}</div></div>;
}
