"use client";
import {useEffect,useState} from "react";
import {ensureCurrentPushSubscription} from "@/lib/push/browser-subscription";

type Props={slug?:string;campaignKey?:string};
export function TimerReminderOptIn({slug,campaignKey}:Props){
 const[visible,setVisible]=useState(false);const[state,setState]=useState<"checking"|"idle"|"busy"|"error">("checking");const identity=slug||campaignKey||"";const reminderText=campaignKey?"a abertura do próximo bolão":"a abertura dos pagamentos";const choiceKey=`bolao-amigos-btp:reminder-choice:${identity||"geral"}`;
 useEffect(()=>{let cancelled=false;let timer:number|undefined;const prepare=async()=>{try{const choice=window.localStorage.getItem(choiceKey);if(choice==="declined"){if(!cancelled){setState("idle");setVisible(false)}return}if(choice==="accepted"){if(!identity||!("serviceWorker" in navigator)||!("PushManager" in window)){if(!cancelled){setState("idle");setVisible(false)}return}const reg=await navigator.serviceWorker.ready;const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(publicKey&&Notification.permission==="granted"){const sub=await ensureCurrentPushSubscription(reg,publicKey);await fetch("/api/push/timer-subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,campaignKey,subscription:sub.toJSON()})})}if(!cancelled){setState("idle");setVisible(false)}return}if(!cancelled){setState("idle");timer=window.setTimeout(()=>setVisible(true),8000)}}catch{if(!cancelled){setState("idle");timer=window.setTimeout(()=>setVisible(true),8000)}}};prepare();return()=>{cancelled=true;if(timer)window.clearTimeout(timer)}},[identity,slug,campaignKey,choiceKey]);
 const decline=()=>{try{window.localStorage.setItem(choiceKey,"declined")}catch{}setVisible(false);setState("idle")};
 const enable=async()=>{try{setState("busy");if(!identity||!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error();const permission=await Notification.requestPermission();if(permission!=="granted"){setState("error");return}const reg=await navigator.serviceWorker.ready;const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error();const sub=await ensureCurrentPushSubscription(reg,publicKey);const res=await fetch("/api/push/timer-subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,campaignKey,subscription:sub.toJSON()})});if(!res.ok)throw new Error();try{window.localStorage.setItem(choiceKey,"accepted")}catch{}setVisible(false);setState("idle")}catch{setState("error")}};
 if(!visible||state==="checking")return null;
 return <div className="reminder-fixed-overlay" role="dialog" aria-modal="true" aria-label="Ativar lembretes"><div className="reminder-fixed-card"><h2>🔔 Quer receber lembretes deste bolão?</h2><p className="muted">Ative neste celular para receber um lembrete a cada 10 dias até {reminderText}.</p><button className="button reminder-3d" type="button" disabled={state==="busy"} onClick={enable}>{state==="busy"?"Ativando...":"🔔 ATIVAR LEMBRETES"}</button><button className="reminder-decline" type="button" disabled={state==="busy"} onClick={decline}>Agora não</button>{state==="error"&&<p className="muted">Não foi possível ativar neste aparelho. Verifique se as notificações estão permitidas.</p>}</div></div>;
}
