"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {sendWaitlistPromotionPush} from "@/lib/push/participant-notifications";

async function requirePoolOwner(poolId:string){const supabase=await createClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Faça login para continuar.");const{data:pool,error}=await supabase.from("pools").select("id,owner_id,total_shares").eq("id",poolId).single();if(error||!pool||pool.owner_id!==auth.user.id)throw new Error("Você não pode alterar este bolão.");return{supabase,pool,userId:auth.user.id}}

export async function addParticipant(input:{poolId:string;name:string;shares:number;phone?:string}){const name=input.name.trim(),shares=Number(input.shares);if(!name)throw new Error("Informe o nome do participante.");if(!Number.isInteger(shares)||shares<1)throw new Error("Informe uma quantidade válida de cotas.");const{supabase,pool}=await requirePoolOwner(input.poolId);const{data:currentParticipants,error:participantsError}=await supabase.from("participants").select("shares,status,is_test").eq("pool_id",input.poolId);if(participantsError)throw new Error(participantsError.message);const usedShares=(currentParticipants??[]).filter(p=>p.status==="confirmed"&&!p.is_test).reduce((sum,p)=>sum+(Number(p.shares)||0),0);if(usedShares+shares>Number(pool.total_shares)){const available=Math.max(0,Number(pool.total_shares)-usedShares);throw new Error(`O bolão possui somente ${available} cota(s) disponível(is).`)}const{data,error}=await supabase.from("participants").insert({pool_id:input.poolId,name,phone:input.phone?.trim()||null,shares,status:"confirmed",payment_status:"pending"}).select().single();if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/participantes");revalidatePath("/carteira");return data}

export async function createTestParticipant(poolId:string){const{supabase,userId}=await requirePoolOwner(poolId);const{count}=await supabase.from("participants").select("id",{count:"exact",head:true}).eq("pool_id",poolId).eq("is_test",true);const suffix=(count??0)>0?` ${(count??0)+1}`:"";const{data,error}=await supabase.from("participants").insert({pool_id:poolId,name:`Cliente Teste InfinitePay${suffix}`,shares:0,status:"confirmed",payment_status:"pending",is_test:true,test_amount_cents:100,notes:"Teste de pagamento InfinitePay — não contabilizar como cota"}).select("id,access_token").single();if(error)throw new Error(error.message);await supabase.from("audit_events").insert({pool_id:poolId,actor_id:userId,event_type:"test_participant_created",entity_type:"participant",entity_id:data.id,details:{amount_cents:100,provider:"infinitepay"}});revalidatePath("/participantes");return data}

export async function cancelParticipant(input:{poolId:string;participantId:string}){if(!input.poolId||!input.participantId)throw new Error("Participante não informado.");const{supabase,userId}=await requirePoolOwner(input.poolId);const{data:participant,error:lookupError}=await supabase.from("participants").select("id,name,status,payment_status").eq("id",input.participantId).eq("pool_id",input.poolId).single();if(lookupError||!participant)throw new Error("Participante não encontrado.");if(participant.status==="cancelled")return participant;if(participant.payment_status==="confirmed")throw new Error("Não cancele participante pago diretamente. Registre primeiro o estorno/correção financeira.");const wasConfirmed=participant.status==="confirmed";const{data,error}=await supabase.from("participants").update({status:"cancelled",waitlist_position:null}).eq("id",input.participantId).eq("pool_id",input.poolId).select().single();if(error)throw new Error(error.message);let promotedId:string|null=null;if(wasConfirmed){const{data:promoted}=await supabase.rpc("promote_next_waitlisted",{p_pool_id:input.poolId});promotedId=promoted??null;if(promotedId){try{await sendWaitlistPromotionPush(promotedId)}catch(e){console.error("Falha ao enviar push de promoção",e)}}}await supabase.from("audit_events").insert({pool_id:input.poolId,actor_id:userId,event_type:"participant_cancelled",entity_type:"participant",entity_id:input.participantId,details:{name:participant.name,promoted_waitlisted_participant_id:promotedId}});revalidatePath("/");revalidatePath("/participantes");revalidatePath("/carteira");return data}
