"use server";
import {revalidatePath} from "next/cache";import {createClient} from "@/lib/supabase/server";
type PaymentMethod="pix"|"cash"|"other";const phoneKey=(v:string)=>v.replace(/\D/g,"");
export async function confirmPayment(input:{poolId:string;participantId:string;amountCents:number;shares:number;method?:PaymentMethod;receiptPath?:string}){
 const shares=Number(input.shares),method:PaymentMethod=input.method==="cash"||input.method==="other"?input.method:"pix";if(!input.poolId||!input.participantId||!Number.isInteger(shares)||shares<=0)throw new Error("Pagamento inválido.");
 const s=await createClient(),{data:a}=await s.auth.getUser();if(!a.user)throw new Error("Faça login para continuar.");const{data:pool}=await s.from("pools").select("owner_id,share_price_cents").eq("id",input.poolId).single();if(!pool||pool.owner_id!==a.user.id)throw new Error("Somente o organizador pode confirmar pagamentos.");const{data:p}=await s.from("participants").select("id,name,phone,shares,payment_status,status").eq("id",input.participantId).eq("pool_id",input.poolId).single();if(!p||p.status==="cancelled")throw new Error("Participante não encontrado.");if(p.payment_status==="confirmed")throw new Error("Este pagamento já foi confirmado.");if(shares!==Number(p.shares))throw new Error("A quantidade de cotas mudou. Atualize a página.");const{data:autoCheckout}=await s.from("payment_checkout_sessions").select("id").eq("participant_id",p.id).in("status",["creating","pending","processing","review_required"]).limit(1).maybeSingle();if(autoCheckout)throw new Error("Existe uma cobrança InfinitePay ativa para este participante. Aguarde o retorno automático antes de confirmar manualmente.");
 const gross=Number(p.shares)*Number(pool.share_price_cents),phone=phoneKey(p.phone||"");let account:any=null;if(phone){const{data}=await s.from("participant_credit_accounts").select("id,balance_cents").eq("owner_id",a.user.id).eq("phone",phone).maybeSingle();account=data}const creditUsed=Math.min(gross,Number(account?.balance_cents||0)),cashPaid=gross-creditUsed;
 const{data:sub}=await s.from("payment_submissions").select("id,receipt_path").eq("participant_id",p.id).eq("status","pending").order("created_at",{ascending:false}).limit(1).maybeSingle(),receipt=input.receiptPath?.trim()||sub?.receipt_path||null;
 const{data:payment,error:pe}=await s.from("payments").insert({pool_id:input.poolId,participant_id:p.id,amount_cents:cashPaid,gross_amount_cents:gross,credit_used_cents:creditUsed,status:"confirmed",payment_method:cashPaid?method:"other",receipt_path:receipt,submitted_at:sub?new Date().toISOString():null,confirmed_at:new Date().toISOString()}).select().single();if(pe)throw new Error(pe.message);
 try{if(account&&creditUsed){const remaining=Number(account.balance_cents)-creditUsed;const{error:u}=await s.from("participant_credit_accounts").update({balance_cents:remaining,updated_at:new Date().toISOString()}).eq("id",account.id).eq("balance_cents",account.balance_cents);if(u)throw u;const{error:l}=await s.from("participant_credit_ledger").insert({account_id:account.id,pool_id:input.poolId,participant_id:p.id,amount_cents:-creditUsed,kind:"use",description:`Crédito utilizado no bolão por ${p.name}`,created_by:a.user.id});if(l)throw l}
  const label=cashPaid===0?"crédito":method==="cash"?"dinheiro":method==="other"?"outro meio":"Pix";if(cashPaid){const{error:w}=await s.from("wallet_transactions").insert({pool_id:input.poolId,payment_id:payment.id,type:"payment_confirmed",amount_cents:cashPaid,shares:Number(p.shares),description:`Pagamento confirmado via ${label}`,created_by:a.user.id});if(w)throw w}if(creditUsed){const{error:w}=await s.from("wallet_transactions").insert({pool_id:input.poolId,payment_id:payment.id,type:"credit_used",amount_cents:creditUsed,shares:0,description:`Crédito abatido de ${p.name}`,created_by:a.user.id});if(w)throw w}const{error:ue}=await s.from("participants").update({payment_status:"confirmed"}).eq("id",p.id);if(ue)throw ue}
 catch(error){await s.from("wallet_transactions").delete().eq("payment_id",payment.id);await s.from("participant_credit_ledger").delete().eq("pool_id",input.poolId).eq("participant_id",p.id).eq("kind","use");if(account&&creditUsed)await s.from("participant_credit_accounts").update({balance_cents:account.balance_cents}).eq("id",account.id);await s.from("payments").delete().eq("id",payment.id);throw error}
 if(sub)await s.from("payment_submissions").update({status:"approved",reviewed_at:new Date().toISOString()}).eq("id",sub.id);await s.from("audit_events").insert({pool_id:input.poolId,actor_id:a.user.id,event_type:"payment_confirmed",entity_type:"payment",entity_id:payment.id,details:{participant_id:p.id,participant_name:p.name,gross_amount_cents:gross,cash_paid_cents:cashPaid,credit_used_cents:creditUsed,shares:Number(p.shares),method}});revalidatePath("/");revalidatePath("/carteira");revalidatePath("/carteira/creditos");revalidatePath("/participantes");return payment;
}
